"""add conversations and chat messages

Revision ID: 136856bc30c8
Revises: 0adb030ae0b4
Create Date: 2026-08-14 14:36:40.402273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136856bc30c8'
down_revision: Union[str, Sequence[str], None] = '0adb030ae0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_company'), 'conversations', ['company'], unique=False)
    op.create_index(op.f('ix_conversations_job_title'), 'conversations', ['job_title'], unique=False)
    op.create_index(op.f('ix_conversations_subject'), 'conversations', ['subject'], unique=False)
    op.create_index(op.f('ix_conversations_token_id'), 'conversations', ['token_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(length=16000), nullable=True),
    sa.Column('content_chars', sa.Integer(), nullable=True),
    sa.Column('truncated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('endpoint', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('finish_reason', sa.String(length=32), nullable=True),
    sa.Column('tool_calls_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tool_names', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('redacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_request_id'), 'chat_messages', ['request_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chat_messages_status'), 'chat_messages', ['status'], unique=False)
    op.create_index(op.f('ix_chat_messages_token_id'), 'chat_messages', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_token_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_status'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_request_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_token_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_subject'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_job_title'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_company'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
