"""add users and tokens

Revision ID: 5a0c81d827cd
Revises: 769fbd196680
Create Date: 2026-08-01 08:50:31.564309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0c81d827cd'
down_revision: Union[str, Sequence[str], None] = '769fbd196680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('subject', sa.String(length=255), nullable=False))
    op.add_column('tokens', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('tokens', sa.Column('job_title', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tokens_company'), 'tokens', ['company'], unique=False)
    op.create_index(op.f('ix_tokens_job_title'), 'tokens', ['job_title'], unique=False)
    op.create_index(op.f('ix_tokens_subject'), 'tokens', ['subject'], unique=False)
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.drop_index(op.f('ix_users_job_type'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    op.drop_column('users', 'job_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_job_type'), 'users', ['job_type'], unique=False)
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_tokens_subject'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_job_title'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_company'), table_name='tokens')
    op.drop_column('tokens', 'job_title')
    op.drop_column('tokens', 'company')
    op.drop_column('tokens', 'subject')
    # ### end Alembic commands ###
